### ISSUE TITLE
Bad interrupt pop count

### ISSUE THREAD

**Issue by Supercip971** [RosesHaveThorns/ProjectAltair#1]
In the interrupt handler you are doing:
```asm

    push byte 0 ; push error code
    push byte 0 ; push interrupt number
```
Where it should be 
push dword 
Because the error code is a dword

You also use:
```asm
add esp, 8
```
For popping 2 dword and not 2 bytes

**Comment by RosesHaveThorns** [comment]
thanks for the help!
fix has been pushed
